images:
  - arch: "x86_64"
    location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img"
  - arch: "aarch64"
    location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-arm64.img"

mounts:
  - location: "/tmp/lima"
    writable: true

ssh:
  forwardAgent: true

provision:
  - mode: system
    script: |
      #!/bin/bash
      set -eux -o pipefail
      apt update
      apt upgrade -y
  - mode: user
    script: |
      #!/bin/bash
      set -eux -o pipefail
      command -v asdf >/dev/null 2>&1 && exit 0
      sudo apt install -y curl git
      git clone https://github.com/asdf-vm/asdf.git ~/.asdf
      cd ~/.asdf
      ASDF_LATEST_VERSION=$(git tag --sort authordate | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | tail -n 1)
      git checkout $ASDF_LATEST_VERSION
      echo '# BEGIN asdf' >> ~/.bashrc
      echo '. "$HOME/.asdf/asdf.sh"' >> ~/.bashrc
      echo '. "$HOME/.asdf/completions/asdf.bash"' >> ~/.bashrc
      echo '# END asdf' >> ~/.bashrc
