images:
  - arch: "x86_64"
    location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img"
  - arch: "aarch64"
    location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-arm64.img"

mounts:
  - location: "~/archive"
    writable: true
  - location: "/tmp/lima"
    writable: true

ssh:
  forwardAgent: true

provision:
  # Create a ~/.bash_profile file
  - mode: user
    script: |
      #!/bin/bash
      set -eux -o pipefail
      if [ -f ~/.bash_profile ]; then exit 0; fi
      tee ~/.bash_profile << 'EOF'
      if [ -f ~/.profile ]; then
        . ~/.profile
      fi
      EOF
  # Install Golang
  - mode: user
    script: |
      #!/bin/bash
      set -eux -o pipefail
      type go && exit 0 || true
      rm -rf /usr/local/go
      curl -L https://go.dev/dl/go1.24.4.linux-arm64.tar.gz | sudo tar -C /usr/local -zxvf -
      sudo tee /etc/profile.d/99-golang.sh << 'EOF'
      export PATH=$PATH:/usr/local/go/bin
      EOF
