images:
  - arch: "x86_64"
    location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img"
  - arch: "aarch64"
    location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-arm64.img"

cpus: 4
memory: 8GiB

mounts:
  - location: "~/archive"
    writable: true
  - location: "/tmp/lima"
    writable: true

ssh:
  forwardAgent: true

provision:
  - mode: system
    script: |
      #!/bin/bash
      set -eux -o pipefail
      apt update
      apt upgrade -y
      apt install -y jq yq
  - mode: user
    script: |
      #!/bin/bash
      set -eux -o pipefail
      command -v asdf >/dev/null 2>&1 && exit 0
      sudo apt install -y curl git
      ASDF_LATEST_VERSION=$(curl -sL https://api.github.com/repos/asdf-vm/asdf/releases/latest | jq -r .tag_name)
      git clone --branch $ASDF_LATEST_VERSION --depth 1 https://github.com/asdf-vm/asdf.git ~/.asdf
      cat << EOF >> ~/.bashrc
      # BEGIN asdf
      . "$HOME/.asdf/asdf.sh"
      . "$HOME/.asdf/completions/asdf.bash"
      # END asdf
      EOF
