images:
  - arch: "x86_64"
    location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img"
  - arch: "aarch64"
    location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-arm64.img"

cpus: 4
memory: 8GiB

mounts:
  - location: "~/archive"
    writable: true
  - location: "/tmp/lima"
    writable: true

ssh:
  forwardAgent: true
