images:
  - arch: "x86_64"
    location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img"
  - arch: "aarch64"
    location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-arm64.img"

mounts:
  - location: "~/archive"
    writable: true
  - location: "/tmp/lima"
    writable: true

ssh:
  forwardAgent: true

provision:
  # Create a ~/.bash_profile file
  - mode: user
    script: |
      #!/bin/bash
      set -eux -o pipefail
      [ -f ~/.bash_profile ] && exit 0
      tee ~/.bash_profile << 'EOF'
      if [ -f ~/.profile ]; then
        . ~/.profile
      fi
      EOF
  # Install Golang
  - mode: user
    script: |
      #!/bin/bash
      set -eux -o pipefail
      type go && exit 0 || true
      rm -rf /usr/local/go
      curl -L https://go.dev/dl/$(curl -fsSL "https://go.dev/VERSION?m=text" | head -n 1).linux-arm64.tar.gz | sudo tar -C /usr/local -zxvf -
      sudo tee /etc/profile.d/99-golang.sh << 'EOF'
      #!/bin/bash
      export GOPATH=$HOME/go
      export GOBIN=$GOPATH/bin
      
      export PATH=$PATH:/usr/local/go/bin
      export PATH=$PATH:$GOBIN
      EOF
  # Install nvm
  - mode: user
    script: |
      #!/bin/bash
      set -eux -o pipefail
      . ~/.bash_profile # これをしないとなぜかnvmのパスが通らない
      type nvm > /dev/null && exit 0 || true
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | PROFILE="$HOME/.bash_profile" bash
  # Install AWS CLI v2
  - mode: user
    script: |
      #!/bin/bash
      set -eux -o pipefail
      type aws && exit 0 || true
      sudo apt-get install -y unzip
      install -d /tmp/awscli && cd /tmp/awscli
      curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd && rm -rf /tmp/awscli
